// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

export const environment = {
  production: false,
  baseUrl: 'http://www.lowcarbon-lighting.com:8080',
  ITEMS_PER_PAGE: 20,
  ITEMS_PER_PAGE_5: 5,
  ITEMS_PER_PAGE_9: 9,
  ITEMS_PER_PAGE_12: 12,
  HOME: 1,
  LCL_RESEARCH: 2,
  TRADE_ADVISORY: 3,
  POLICY_STANDARD: 4,
  EXPERT_VIEWS: 5,
  PROJECT_DEMO: 6,
  BIDDING_PROCUREMENT: 7,
  OFFICIAL_JOURNAL: 8,
  DOCUMENT_LIBRARY: 9,
  ONLINE_COURSE: 10,
  EXPERT_LIBRARY: 11,
  BRIEF_INTRO: 12,
  CENTER_NEWS: 13,
  ABOUT_US: 14,
  CONTACT_US: 15,
  DOMESTIC_HOTSPOT: 16,
  INTERNATIONAL_HOTSPOT: 17,
  CONVENTION_TRACKING: 18,
  CENTRALGOV_DOC: 19,
  LOCALGOV_DOC: 20,
  INTERNATIONAL_STD: 21,
  SELECTED_CASE: 22,
  AUTHORITY_COMMENT: 23,
  PROF_BOOK: 24,
  ACADEMIC_PAPER: 25,
  RESEARCH_REPORT: 26,
  VIDEO_IMAGE: 27,
  RELATED_WEBSITES: 28,
};
